import 'package:shree_laxmi_box_stocks/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.areYouSureYouWantToExitTheApp: "Are you sure you want to exit the app?",
  AppStrings.no: "No",
  AppStrings.yesExit: "Yes, exit",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.hello: "Hello ",
  AppStrings.noDataFound: "No data found",
  AppStrings.settings: "Settings",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "Log Out",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterPhoneNumber: "Please enter phone number",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password",
  AppStrings.createOrder: "Create Order",
  AppStrings.selectOrCaptureAImage: "Select or Capture a Image",
  AppStrings.select: "Select",
  AppStrings.camera: "Camera",
  AppStrings.gallery: "Gallery",
  AppStrings.successfullyDownloadedAtDownloadFolder: "Successfully downloaded at 'Download' folder.",
  AppStrings.downloadFailedPleaseTryAgain: "Download failed, Please try again.",
  AppStrings.update: 'Update',
  AppStrings.newVersionAvailable: 'A new version is available. Please upgrade to it.',
  AppStrings.pleaseEnterValidPhoneNumber: "Please enter valid phone number",
  AppStrings.sessionExpire: "Session Expire.",
  AppStrings.save: "Save",
  AppStrings.pendingOrders: "Pending Orders",
  AppStrings.pleaseEnterPartyName: "Please enter party name",
  AppStrings.pleaseSelectParty: "Please select party",
  AppStrings.enterPartyPhone: "Enter party phone",
  AppStrings.partyEmail: "Party Email",
  AppStrings.enterPartyEmail: "Enter party email",
  AppStrings.pleaseEnterValidEmail: "Please enter valid email",
  AppStrings.purchaseOrderNumber: "Purchase Order Number",
  AppStrings.enterPurchaseOrderNumber: "Enter purchase order number",
  AppStrings.pleaseEnterPurchaseOrderNumber: "Please enter purchase order number",
  AppStrings.selectPartyName: "Select party name",
  AppStrings.selectParty: "Select party",
  AppStrings.boxSize: "Box Size(L × B) :",
  AppStrings.boxQuantity: "Box Quantity",
  AppStrings.l: "L",
  AppStrings.b: "B",
  AppStrings.h: "H",
  AppStrings.pleaseEnterBoxSize: "Please enter box size",
  AppStrings.pleaseEnterValidBoxSize: "Please enter valid box size",
  AppStrings.enterBoxQuantity: "Enter box quantity",
  AppStrings.pleaseEnterBoxQuantity: "Please enter box quantity",
  AppStrings.boxType: "Box Type :",
  AppStrings.pellet: "Pellet",
  AppStrings.box: "Box",
  AppStrings.cage: "Cage",
  AppStrings.wayType: "Way Type :",
  AppStrings.twoWay: "2 way",
  AppStrings.fourWay: "4 way",
  AppStrings.boxPurityType: "Box Purity Type :",
  AppStrings.full: "Full",
  AppStrings.topPatiya: "Top Patiya :",
  AppStrings.topPatiyaSize: "Top Patiya Size(L × B × H) :",
  AppStrings.enterTopPatiyaSize: "Enter top patiya size",
  AppStrings.pleaseEnterTopPatiyaSize: "Please enter top patiya size",
  AppStrings.topPatiyaQuantity: "Top Patiya Quantity",
  AppStrings.enterTopPatiyaQuantity: "Enter top patiya quantity",
  AppStrings.pleaseEnterQuantity: "Please enter quantity",
  AppStrings.pleaseEnterSize: "Please enter size",
  AppStrings.pleaseEnterValidSize: "Please enter valid size",
  AppStrings.sleeperPatiyaSize: "Sleeper Patiya Size(L × B × H) :",
  AppStrings.sleeperPatiyaQuantity: "Sleeper Patiya Quantity",
  AppStrings.enterSleeperPatiyaQuantity: "Enter sleeper patiya quantity",
  AppStrings.ghodiPatiyaSize: "Ghodi Patiya Size(L × B × H) :",
  AppStrings.ghodiPatiyaQuantity: "Ghodi Patiya Quantity",
  AppStrings.enterGhodiPatiyaQuantity: "Enter ghodi patiya quantity",
  AppStrings.blockSize: "Block Size(L × B × H) :",
  AppStrings.blockQuantity: "Block Quantity",
  AppStrings.enterBlockQuantity: "Enter block quantity",
  AppStrings.pleaseSelectBoxType: "Please select box type",
  AppStrings.pleaseSelectWayType: "Please select way type",
  AppStrings.pleaseSelectBoxPurityType: "Please select box purity type",
  AppStrings.deliveryDate: "Delivery Date",
  AppStrings.selectDeliveryDate: "Select delivery date",
  AppStrings.pleaseSelectDeliveryDate: "Please select delivery date",
  AppStrings.searchParty: "Search party",
  AppStrings.editParty: "Edit Party",
  AppStrings.editPartyName: "Edit Party Name",
  AppStrings.editPhoneNumber: "Edit Phone Number",
  AppStrings.editEmail: "Edit Email",
  AppStrings.orderNumber: "Order Number",
  AppStrings.size: "Size",
  AppStrings.quantity: "Quantity",
  AppStrings.sleeperPatiya: "Sleeper Patiya: ",
  AppStrings.ghodiPatiya: "Ghodi Patiya: ",
  AppStrings.block: "Block: ",
};
