import 'package:shree_laxmi_box_stocks/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.areYouSureYouWantToExitTheApp: "Are you sure you want to exit the app?",
  AppStrings.no: "No",
  AppStrings.yesExit: "Yes, exit",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.hello: "Hello ",
  AppStrings.noDataFound: "No data found",
  AppStrings.settings: "Settings",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "Log Out",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterPhoneNumber: "Please enter phone number",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password",
  AppStrings.createOrder: "Create Order",
  AppStrings.selectOrCaptureAImage: "Select or Capture a Image",
  AppStrings.select: "Select",
  AppStrings.camera: "Camera",
  AppStrings.gallery: "Gallery",
  AppStrings.successfullyDownloadedAtDownloadFolder: "Successfully downloaded at 'Download' folder.",
  AppStrings.downloadFailedPleaseTryAgain: "Download failed, Please try again.",
  AppStrings.update: 'Update',
  AppStrings.newVersionAvailable: 'A new version is available. Please upgrade to it.',
  AppStrings.pleaseEnterValidPhoneNumber: "Please enter valid phone number",
  AppStrings.sessionExpire: "Session Expire.",
  AppStrings.save: "Save",
  AppStrings.pendingOrders: "Pending Orders",
  AppStrings.pleaseEnterPartyName: "Please enter party name",
  AppStrings.pleaseSelectParty: "Please select party",
};
