import 'package:shree_laxmi_box_stocks/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.areYouSureYouWantToExitTheApp: "શું તમે ખરેખર એપ્લિકેશનમાંથી બહાર નીકળવા માંગો છો?",
  AppStrings.no: "ના",
  AppStrings.yesExit: "હા, બહાર નીકળો",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.hello: "નમસ્તે ",
  AppStrings.noDataFound: "કોઈ ડેટા મળ્યો નથી",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "લૉગ આઉટ",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterPhoneNumber: "કૃપા કરીને ફોન નંબર દાખલ કરો",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો",
  AppStrings.createOrder: "ઓર્ડર ઉમેરો",
  AppStrings.selectOrCaptureAImage: "છબી પસંદ કરો અથવા કેપ્ચર કરો",
  AppStrings.select: "પસંદ કરો",
  AppStrings.camera: "કેમેરા",
  AppStrings.gallery: "ગેલેરી",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' ફોલ્ડર પર સફળતાપૂર્વક ડાઉનલોડ કર્યું.",
  AppStrings.downloadFailedPleaseTryAgain: "ડાઉનલોડ નિષ્ફળ થયું, કૃપા કરીને ફરી પ્રયાસ કરો.",
  AppStrings.update: 'અપડેટ કરો',
  AppStrings.newVersionAvailable: 'નવું સંસ્કરણ ઉપલબ્ધ છે. કૃપા કરીને તેમાં અપગ્રેડ કરો.',
  AppStrings.pleaseEnterValidPhoneNumber: "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો",
  AppStrings.sessionExpire: "સત્ર સમાપ્ત.",
  AppStrings.save: "સાચવો",
  AppStrings.pendingOrders: "બાકી ઓર્ડર",
  AppStrings.pleaseEnterPartyName: "કૃપા કરીને પાર્ટીનું નામ દાખલ કરો",
  AppStrings.pleaseSelectParty: "કૃપા કરીને પાર્ટી પસંદ કરો",
};
