import 'package:shree_laxmi_box_stocks/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.areYouSureYouWantToExitTheApp: "શું તમે ખરેખર એપ્લિકેશનમાંથી બહાર નીકળવા માંગો છો?",
  AppStrings.no: "ના",
  AppStrings.yesExit: "હા, બહાર નીકળો",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.hello: "નમસ્તે ",
  AppStrings.noDataFound: "કોઈ ડેટા મળ્યો નથી",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "લૉગ આઉટ",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterPhoneNumber: "કૃપા કરીને ફોન નંબર દાખલ કરો",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો",
  AppStrings.createOrder: "ઓર્ડર ઉમેરો",
  AppStrings.selectOrCaptureAImage: "છબી પસંદ કરો અથવા કેપ્ચર કરો",
  AppStrings.select: "પસંદ કરો",
  AppStrings.camera: "કેમેરા",
  AppStrings.gallery: "ગેલેરી",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' ફોલ્ડર પર સફળતાપૂર્વક ડાઉનલોડ કર્યું.",
  AppStrings.downloadFailedPleaseTryAgain: "ડાઉનલોડ નિષ્ફળ થયું, કૃપા કરીને ફરી પ્રયાસ કરો.",
  AppStrings.update: 'અપડેટ કરો',
  AppStrings.newVersionAvailable: 'નવું સંસ્કરણ ઉપલબ્ધ છે. કૃપા કરીને તેમાં અપગ્રેડ કરો.',
  AppStrings.pleaseEnterValidPhoneNumber: "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો",
  AppStrings.sessionExpire: "સત્ર સમાપ્ત.",
  AppStrings.save: "સાચવો",
  AppStrings.pendingOrders: "બાકી ઓર્ડર",
  AppStrings.pleaseEnterPartyName: "કૃપા કરીને પાર્ટીનું નામ દાખલ કરો",
  AppStrings.pleaseSelectParty: "કૃપા કરીને પાર્ટી પસંદ કરો",
  AppStrings.enterPartyPhone: "પાર્ટી ફોન દાખલ કરો",
  AppStrings.partyEmail: "પાર્ટી ઈમેઇલ",
  AppStrings.enterPartyEmail: "પાર્ટી ઈમેઇલ દાખલ કરો",
  AppStrings.pleaseEnterValidEmail: "મહેરબાની કરી માન્ય ઈમેઇલ દાખલ કરો",
  AppStrings.purchaseOrderNumber: "ખરીદી ઓર્ડર નંબર",
  AppStrings.enterPurchaseOrderNumber: "ખરીદી ઓર્ડર નંબર દાખલ કરો",
  AppStrings.pleaseEnterPurchaseOrderNumber: "મહેરબાની કરી ખરીદી ઓર્ડર નંબર દાખલ કરો",
  AppStrings.selectPartyName: "પાર્ટીનું નામ પસંદ કરો",
  AppStrings.selectParty: "પાર્ટી પસંદ કરો",
  AppStrings.boxSize: "બોક્સ સાઈઝ (લંબાઈ × પહોળાઈ) :",
  AppStrings.boxQuantity: "બોક્સ માત્રા",
  AppStrings.l: "L",
  AppStrings.b: "B",
  AppStrings.h: "H",
  AppStrings.pleaseEnterBoxSize: "મહેરબાની કરી બોક્સ સાઈઝ દાખલ કરો",
  AppStrings.pleaseEnterValidBoxSize: "મહેરબાની કરી માન્ય બોક્સ સાઈઝ દાખલ કરો",
  AppStrings.enterBoxQuantity: "બોક્સ માત્રા દાખલ કરો",
  AppStrings.pleaseEnterBoxQuantity: "મહેરબાની કરી બોક્સ માત્રા દાખલ કરો",
  AppStrings.boxType: "બોક્સ પ્રકાર :",
  AppStrings.pellet: "પેલેટ",
  AppStrings.box: "બોક્સ",
  AppStrings.cage: "કેજ",
  AppStrings.wayType: "વે ટાઈપ :",
  AppStrings.twoWay: "2 વે",
  AppStrings.fourWay: "4 વે",
  AppStrings.boxPurityType: "બોક્સ શુદ્ધતા પ્રકાર :",
  AppStrings.full: "સંપૂર્ણ",
  AppStrings.topPatiya: "ટોપ પટિયા :",
  AppStrings.topPatiyaSize: "ટોપ પટિયા સાઈઝ (લંબાઈ × પહોળાઈ × ઊંચાઈ) :",
  AppStrings.enterTopPatiyaSize: "ટોપ પટિયા સાઈઝ દાખલ કરો",
  AppStrings.pleaseEnterTopPatiyaSize: "મહેરબાની કરી ટોપ પટિયા સાઈઝ દાખલ કરો",
  AppStrings.topPatiyaQuantity: "ટોપ પટિયા માત્રા",
  AppStrings.enterTopPatiyaQuantity: "ટોપ પટિયા માત્રા દાખલ કરો",
  AppStrings.pleaseEnterQuantity: "મહેરબાની કરી માત્રા દાખલ કરો",
  AppStrings.pleaseEnterSize: "મહેરબાની કરી સાઈઝ દાખલ કરો",
  AppStrings.pleaseEnterValidSize: "મહેરબાની કરી માન્ય સાઈઝ દાખલ કરો",
  AppStrings.sleeperPatiyaSize: "સ્લીપર પટિયા સાઈઝ (લંબાઈ × પહોળાઈ × ઊંચાઈ) :",
  AppStrings.sleeperPatiyaQuantity: "સ્લીપર પટિયા માત્રા",
  AppStrings.enterSleeperPatiyaQuantity: "સ્લીપર પટિયા માત્રા દાખલ કરો",
  AppStrings.ghodiPatiyaSize: "ઘોડી પટિયા સાઈઝ (લંબાઈ × પહોળાઈ × ઊંચાઈ) :",
  AppStrings.ghodiPatiyaQuantity: "ઘોડી પટિયા માત્રા",
  AppStrings.enterGhodiPatiyaQuantity: "ઘોડી પટિયા માત્રા દાખલ કરો",
  AppStrings.blockSize: "બ્લોક સાઈઝ (લંબાઈ × પહોળાઈ × ઊંચાઈ) :",
  AppStrings.blockQuantity: "બ્લોક માત્રા",
  AppStrings.enterBlockQuantity: "બ્લોક માત્રા દાખલ કરો",
  AppStrings.pleaseSelectBoxType: "મહેરબાની કરી બોક્સ પ્રકાર પસંદ કરો",
  AppStrings.pleaseSelectWayType: "મહેરબાની કરી વે ટાઈપ પસંદ કરો",
  AppStrings.pleaseSelectBoxPurityType: "મહેરબાની કરી બોક્સ શુદ્ધતા પ્રકાર પસંદ કરો",
  AppStrings.deliveryDate: "ડિલિવરી તારીખ",
  AppStrings.selectDeliveryDate: "ડિલિવરી તારીખ પસંદ કરો",
  AppStrings.pleaseSelectDeliveryDate: "મહેરબાની કરી ડિલિવરી તારીખ પસંદ કરો",
  AppStrings.searchParty: "પાર્ટી શોધો",
  AppStrings.editParty: "સંપાદન પાર્ટી",
  AppStrings.editPartyName: "પાર્ટીનું નામ સંપાદિત કરો",
  AppStrings.editPhoneNumber: "ફોન નંબર સંપાદિત કરો",
};
