import 'package:shree_laxmi_box_stocks/Constants/app_strings.dart';

Map<String, String> hiIN = <String, String>{
  AppStrings.login: "लॉग इन करें",
  AppStrings.areYouSureYouWantToExitTheApp: "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
  AppStrings.no: "नहीं",
  AppStrings.yesExit: "हाँ, बाहर निकलें",
  AppStrings.temporaryServiceIsNotAvailable: "अस्थायी सेवा उपलब्ध नहीं है।",
  AppStrings.hello: "नमस्ते ",
  AppStrings.noDataFound: "डाटा प्राप्त नहीं हुआ",
  AppStrings.settings: "सेटिंग्स",
  AppStrings.changeLanguage: "भाषा बदलें",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'लॉग आउट',
  AppStrings.phoneNumber: "फ़ोन नंबर",
  AppStrings.enterPhoneNumber: "फोन नंबर दर्ज",
  AppStrings.pleaseEnterPhoneNumber: "कृपया फ़ोन नंबर दर्ज करें",
  AppStrings.password: "पासवर्ड",
  AppStrings.enterPassword: "पासवर्ड दर्ज करे",
  AppStrings.pleaseEnterPassword: "कृपया पासवर्ड दर्ज करें",
  AppStrings.createOrder: "ऑर्डर बनाएँ",
  AppStrings.selectOrCaptureAImage: "इस छवि को चुनें या कैप्चर करें",
  AppStrings.select: "चुनना",
  AppStrings.camera: "कैमरा",
  AppStrings.gallery: "गैलरी",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' फ़ोल्डर में सफलतापूर्वक डाउनलोड किया गया।",
  AppStrings.downloadFailedPleaseTryAgain: "डाउनलोड विफल, कृपया पुनः प्रयास करें।",
  AppStrings.update: 'अद्यतन',
  AppStrings.newVersionAvailable: 'एक नया संस्करण उपलब्ध है। कृपया इसे अपग्रेड करें।',
  AppStrings.pleaseEnterValidPhoneNumber: "कृपया एक वैध फोन नंबर डालें",
  AppStrings.sessionExpire: "सत्र समाप्ति।",
  AppStrings.save: "संचय",
  AppStrings.pendingOrders: "लंबित ऑर्डर",
  AppStrings.pleaseEnterPartyName: "कृपया पार्टी का नाम दर्ज करें",
  AppStrings.pleaseSelectParty: "कृपया पार्टी का चयन करें",
  AppStrings.enterPartyPhone: "पार्टी फोन दर्ज करें",
  AppStrings.partyEmail: "पार्टी ईमेल",
  AppStrings.enterPartyEmail: "पार्टी ईमेल दर्ज करें",
  AppStrings.pleaseEnterValidEmail: "कृपया मान्य ईमेल दर्ज करें",
  AppStrings.purchaseOrderNumber: "खरीद ऑर्डर संख्या",
  AppStrings.enterPurchaseOrderNumber: "खरीद ऑर्डर संख्या दर्ज करें",
  AppStrings.pleaseEnterPurchaseOrderNumber: "कृपया खरीद ऑर्डर संख्या दर्ज करें",
  AppStrings.selectPartyName: "पार्टी का नाम चुनें",
  AppStrings.selectParty: "पार्टी चुनें",
  AppStrings.boxSize: "बॉक्स आकार (लंबाई × चौड़ाई) :",
  AppStrings.boxQuantity: "बॉक्स मात्रा",
  AppStrings.l: "L",
  AppStrings.b: "B",
  AppStrings.h: "H",
  AppStrings.pleaseEnterBoxSize: "कृपया बॉक्स आकार दर्ज करें",
  AppStrings.pleaseEnterValidBoxSize: "कृपया मान्य बॉक्स आकार दर्ज करें",
  AppStrings.enterBoxQuantity: "बॉक्स मात्रा दर्ज करें",
  AppStrings.pleaseEnterBoxQuantity: "कृपया बॉक्स मात्रा दर्ज करें",
  AppStrings.boxType: "बॉक्स प्रकार :",
  AppStrings.pellet: "पैलेट",
  AppStrings.box: "बॉक्स",
  AppStrings.cage: "केज",
  AppStrings.wayType: "वे प्रकार :",
  AppStrings.twoWay: "2 वे",
  AppStrings.fourWay: "4 वे",
  AppStrings.boxPurityType: "बॉक्स शुद्धता प्रकार :",
  AppStrings.full: "पूर्ण",
  AppStrings.topPatiya: "टॉप पटिया :",
  AppStrings.topPatiyaSize: "टॉप पटिया आकार (लंबाई × चौड़ाई × ऊँचाई) :",
  AppStrings.enterTopPatiyaSize: "टॉप पटिया आकार दर्ज करें",
  AppStrings.pleaseEnterTopPatiyaSize: "कृपया टॉप पटिया आकार दर्ज करें",
  AppStrings.topPatiyaQuantity: "टॉप पटिया मात्रा",
  AppStrings.enterTopPatiyaQuantity: "टॉप पटिया मात्रा दर्ज करें",
  AppStrings.pleaseEnterQuantity: "कृपया मात्रा दर्ज करें",
  AppStrings.pleaseEnterSize: "कृपया आकार दर्ज करें",
  AppStrings.pleaseEnterValidSize: "कृपया मान्य आकार दर्ज करें",
  AppStrings.sleeperPatiyaSize: "स्लीपर पटिया आकार (लंबाई × चौड़ाई × ऊँचाई) :",
  AppStrings.sleeperPatiyaQuantity: "स्लीपर पटिया मात्रा",
  AppStrings.enterSleeperPatiyaQuantity: "स्लीपर पटिया मात्रा दर्ज करें",
  AppStrings.ghodiPatiyaSize: "घोड़ी पटिया आकार (लंबाई × चौड़ाई × ऊँचाई) :",
  AppStrings.ghodiPatiyaQuantity: "घोड़ी पटिया मात्रा",
  AppStrings.enterGhodiPatiyaQuantity: "घोड़ी पटिया मात्रा दर्ज करें",
  AppStrings.blockSize: "ब्लॉक आकार (लंबाई × चौड़ाई × ऊँचाई) :",
  AppStrings.blockQuantity: "ब्लॉक मात्रा",
  AppStrings.enterBlockQuantity: "ब्लॉक मात्रा दर्ज करें",
  AppStrings.pleaseSelectBoxType: "कृपया बॉक्स प्रकार चुनें",
  AppStrings.pleaseSelectWayType: "कृपया वे प्रकार चुनें",
  AppStrings.pleaseSelectBoxPurityType: "कृपया बॉक्स शुद्धता प्रकार चुनें",
  AppStrings.deliveryDate: "डिलीवरी तिथि",
  AppStrings.selectDeliveryDate: "डिलीवरी तिथि चुनें",
  AppStrings.pleaseSelectDeliveryDate: "कृपया डिलीवरी तिथि चुनें",
  AppStrings.searchParty: "पार्टी खोजें",
  AppStrings.editParty: "पार्टी संपादित करें",
  AppStrings.editPartyName: "पार्टी का नाम संपादित करें",
  AppStrings.editPhoneNumber: "फोन नंबर संपादित करें",
  AppStrings.editEmail: "ईमेल संपादित करें",
  AppStrings.orderNumber: "ऑर्डर संख्या",
  AppStrings.size: "माप",
  AppStrings.quantity: "मात्रा",
  AppStrings.sleeperPatiya: "स्लीपर पाटिया: ",
  AppStrings.ghodiPatiya: "घोड़ी पाटिया: ",
  AppStrings.block: "ब्लॉक: ",
};
