import 'package:shree_laxmi_box_stocks/Constants/app_strings.dart';

Map<String, String> hiIN = <String, String>{
  AppStrings.login: "लॉग इन करें",
  AppStrings.areYouSureYouWantToExitTheApp: "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
  AppStrings.no: "नहीं",
  AppStrings.yesExit: "हाँ, बाहर निकलें",
  AppStrings.temporaryServiceIsNotAvailable: "अस्थायी सेवा उपलब्ध नहीं है।",
  AppStrings.hello: "नमस्ते ",
  AppStrings.noDataFound: "डाटा प्राप्त नहीं हुआ",
  AppStrings.settings: "सेटिंग्स",
  AppStrings.changeLanguage: "भाषा बदलें",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'लॉग आउट',
  AppStrings.phoneNumber: "फ़ोन नंबर",
  AppStrings.enterPhoneNumber: "फोन नंबर दर्ज",
  AppStrings.pleaseEnterPhoneNumber: "कृपया फ़ोन नंबर दर्ज करें",
  AppStrings.password: "पासवर्ड",
  AppStrings.enterPassword: "पासवर्ड दर्ज करे",
  AppStrings.pleaseEnterPassword: "कृपया पासवर्ड दर्ज करें",
  AppStrings.createOrder: "ऑर्डर बनाएँ",
  AppStrings.selectOrCaptureAImage: "इस छवि को चुनें या कैप्चर करें",
  AppStrings.select: "चुनना",
  AppStrings.camera: "कैमरा",
  AppStrings.gallery: "गैलरी",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' फ़ोल्डर में सफलतापूर्वक डाउनलोड किया गया।",
  AppStrings.downloadFailedPleaseTryAgain: "डाउनलोड विफल, कृपया पुनः प्रयास करें।",
  AppStrings.update: 'अद्यतन',
  AppStrings.newVersionAvailable: 'एक नया संस्करण उपलब्ध है। कृपया इसे अपग्रेड करें।',
  AppStrings.pleaseEnterValidPhoneNumber: "कृपया एक वैध फोन नंबर डालें",
  AppStrings.sessionExpire: "सत्र समाप्ति।",
  AppStrings.save: "संचय",
  AppStrings.pendingOrders: "लंबित ऑर्डर",
  AppStrings.pleaseEnterPartyName: "कृपया पार्टी का नाम दर्ज करें",
  AppStrings.pleaseSelectParty: "कृपया पार्टी का चयन करें",
};
