name: shree_laxmi_box_stocks
description: "A stock management of Shree Laxmi Box."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  #State management Libs
  get: ^4.7.2

  #Network & Storage Libs
  dio: ^5.8.0+1
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  json_annotation: ^4.9.0

  #Widget Libs
  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  dropdown_search: ^6.0.2
  flutter_image_compress: ^2.4.0
  syncfusion_flutter_core: ^28.2.7
  syncfusion_flutter_pdfviewer: ^28.2.7
  font_awesome_flutter: ^10.8.0
  flutter_staggered_animations: ^1.1.1
  collection: ^1.19.0
  flutter_native_splash: ^2.4.5
  lottie: ^3.3.1

  #Files Libs
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  path_provider: ^2.1.5

  #Device & App Libs
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.2

dependency_overrides:
  collection: ^1.19.1
  intl: ^0.20.2
  path: ^1.9.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100

flutter_native_splash:
  image: assets/images/native_splash_image.png
  color: "#1d232a"
  android_12:
    image: assets/images/native_splash_image.png
    color: "#1d232a"